### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by Feierprinz** [nicolashimmelmann/ESP_GWY433#1]
Hi Nicolas,

can you provide a wiring-Schema or an Diagram?

thanks and bet regards,

Swen

**Comment by nicolashimmelmann** [comment]
Hi Swen,

sure, that's not too complicated. Just connect the pins of your ESP8266 board and the 433 MHz sender module as follows. In my case it is a Wemos D1 mini board.

| Wemos D1 mini pin | 433 MHz sender pin |
|----------|----------|
| 5V | VCC |
| GND | GND |
| D1 | DATA |

In my case, that pin D1 on the board corresponds to pin 5 in the Arduino framework.

The pin for data can be changed in the code if needed. See this line:
https://github.com/nicolashimmelmann/esp-gwy433/blob/master/src/main.cpp#L37

Regards
Nicolas

**Comment by Feierprinz** [comment]
Thanks so so much :)
