### ISSUE TITLE
Compile Error :(

### ISSUE THREAD

**Issue by Feierprinz** [nicolashimmelmann/ESP_GWY433#2]
Hi Nicolas,

sorry das ich nochmal nerve. Ich bekomme es einfach nicht compiliert.
Die fehlende WifiCredentials.h habe ich schon beseitigen können:
//Insert your WiFi credentials here
static const char* _WIFI_SSID = "Fritz!Box";
static const char* _WIFI_PSK = "PASSWORD1234";

Aber irgendwie meckert der bei der GWY433.cpp im Abschnitt void GWY433::listen()
lib\gwy433\GWY433.cpp:39:22: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'String')

Die komplette Debug-Meldung habe ich angehangen.
[Debug.txt](https://github.com/nicolashimmelmann/esp-gwy433/files/15067188/Debug.txt)

Kannst du mir nochmal helfen?

LG
Swen

**Comment by nicolashimmelmann** [comment]
Hi,

den Code hab ich vor ca. 6 Jahren geschrieben und seitdem nie an die neuen Libraries / SDKs angepasst. Und auch nicht besonders gut dokumentiert, wie du gemerkt hast ;-) Ich schau mal, dass ich den auf den aktuellen Stand bringe. Melde mich hier wenn es wieder läuft

**Comment by nicolashimmelmann** [comment]
Das war nur ein Quickfix. Der Arduino "String" musste noch zu einem c_str konvertiert werden, damit das mit dem Stringstream so funktioniert. Teste mal, ob es nun läuft.

**Comment by Feierprinz** [comment]
Hat wunderbar funktioniert, daaaaanke ☺️
